server:
  port: 9095

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb2
    driver: com.mysql.jdbc.Driver
    username: root
    password: 123456
    testWhileIdle: true
    validationQuery: SELECT 1

